### ISSUE TITLE
Rows and columns of the result table are misaligned in the terminal

### ISSUE THREAD

**Issue by Xuanyu-Lyu** [rborder/xftsim#8]
![WeChat3af810b92b91acad0682a238d1ac3269](https://github.com/rborder/xftsim/assets/89999350/adfd96d8-161d-4a93-bfed-93995cb0faba)

The tables from `test_sim.results` are a little hard to check because some of the column names are mismatched with the correspondent columns. 

Thanks!

**Comment by rborder** [comment]
The solution here is access the items individually, e.g. `test_sim.results['sample_statistics']['corr']
